name: dnabert2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
dependencies:
  - python=3.8
  - pytorch=2.3.1
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pandas<2.2
  - numpy<1.25
  - matplotlib<3.8
  - scikit-learn>=1.2.2,<1.4
  - tqdm>=4.67.1
  - pip
  - pip:
    - einops==0.6.1
    - transformers>=4.41.0
    - peft>=0.10.0
    - omegaconf==2.3.0
    - evaluate==0.4.0
    - accelerate>=0.30.0
    - logomaker